# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='图片浏览数')),
            ],
            options={
                'verbose_name': '浏览表',
                'verbose_name_plural': '浏览表',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_change_question', '可以修改图片信息'), ('can_add_question', '可以添加图片信息'), ('can_change_question_status', '可以修改图片状态')), 'verbose_name': '图片评论表', 'verbose_name_plural': '图片评论表'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ManyToManyField(to='picture.Category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='counts',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Picture', verbose_name='图片'),
        ),
    ]
