# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_change_question', '可以修改图片信息'), ('can_add_question', '可以添加图片信息'), ('can_change_question_status', '可以修改图片状态')), 'verbose_name': '图片评论表', 'verbose_name_plural': '图片评论表'},
        ),
        migrations.AddField(
            model_name='picture',
            name='count',
            field=models.IntegerField(null=True, verbose_name='图片浏览数'),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_name',
            field=models.CharField(max_length=100, null=True, verbose_name='图片名字'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ManyToManyField(to='picture.Category', verbose_name='所属分类'),
        ),
    ]
