# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20190821_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='photo_url',
            field=models.CharField(default='photo', max_length=100, verbose_name='图片本地地址'),
            preserve_default=False,
        ),
    ]
